version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - app
    volumes:
      - pgdata:/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    image: contacts_app:1.0
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - app
    volumes:
      - ./backend:/code
    depends_on:
      - db
    links:
      - db
    entrypoint: /code/entrypoint.sh

networks:
  app:

volumes:
  pgdata:
