version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - app
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    links:
      - db
    entrypoint: /backend/entrypoint.sh

  frontend:
    build: ./frontend
    stdin_open: true
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - app
    volumes:
      - ./frontend/my-app:/frontend

networks:
  app:

volumes:
  db-data:
  frontend:
  backend:
